### ISSUE TITLE
Update hasPreviousPage logic to match spec changes

### ISSUE THREAD

**Issue by ndreynolds** [absinthe-graphql/absinthe_relay#111]
I noticed that currently `Connection.from_list/3` and `Connection.from_query/4` always return `has_previous_page: false` when paginating in the forward direction (without specifying `last`).  There's some explanation for it here:

https://github.com/absinthe-graphql/absinthe_relay/blob/6c2f5aaa6b6adec831cdd0f1f0180e5fa8693678/lib/absinthe/relay/connection.ex#L287-L290

Looking at the spec, it seems that this was since changed:

https://github.com/facebook/relay/commit/234642a19962dad0639395ff364b637a64b7f87a#diff-fd1d3b3cc481fe7ab6c5094b13d64e4b

It now provides the following algorithm:

https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields
```
HasPreviousPage(allEdges, before, after, first, last)

 1. If last is set:
     a. Let edges be the result of calling ApplyCursorsToEdges(allEdges, before, after).
     b. If edges contains more than last elements return true, otherwise false.
 2. If after is set:
     a. If the server can efficiently determine that elements exist prior to after, 
        return true.
 3. Return false.
```

So assuming there is a previous page and we can efficiently determine this, it seems okay to return `true` now, even if `last` is unset.

Is this something that can be updated?  It should probably be updated for the other direction as well.  If so, I'd be happy to work on a PR.  It'd be really helpful for us when implementing pagination with next/previous buttons.

**Comment by bruce** [comment]
We’d definitely be interested in a PR to handle these changes. Please let us know if we can help!
