### ISSUE TITLE
Connection offset and limit computation doesn't handle nil correctly

### ISSUE THREAD

**Issue by BenoitHiller** [absinthe-graphql/absinthe_relay#113]
`Absinthe.Relay.Connection.offset_and_limit_for_query` doesn't ignore `nil` values for `first` and `last`. Note below that it returns an unexpected value.

    alias Absinthe.Relay.Connection
    Connection.offset_and_limit_for_query(
      %{
        before: Connection.offset_to_cursor(10),
        last: 10,
        after: nil
      },
      %{}
    ) == {:ok, 10, nil}

    Connection.offset_and_limit_for_query(
      %{
        before: Connection.offset_to_cursor(10),
        last: 10
      },
      %{}
    ) == {:ok, 0, 10}

This results in the following error (on 1.4.2) if you let the nil param get passed into `Absinthe.Relay.Connection.from_query`:

    ** (ArithmeticError) bad argument in arithmetic expression
        (absinthe_relay) lib/absinthe/relay/connection.ex:385: Absinthe.Relay.Connection.from_query/4

I see that at some point guards were added to fix the same problem on before/after.

**Comment by bruce** [comment]
Thanks @BenoitHiller; we'll look at this after taking care of some related work in that area in #110.

**Comment by benwilson512** [comment]
This looks to have been addressed in that PR.
