### ISSUE TITLE
Invalid types are allowed to go through the node field's resolution

### ISSUE THREAD

**Issue by satom99** [absinthe-graphql/absinthe_relay#145]
When a properly encoded ID containing an invalid type is provided when
querying the node field, one of the defined node objects is queried at random
with the received encoded value. So the value returned by the translator is
ignored and because the type is invalid, a seemingly random type is queried.

An example could be to use the default Base64 translator and provide the
simple value `YTpi` as the ID, which is basically the string `"a:b"` encoded.
The default translator will parse this just fine and pass down `a` as the type
and `b` as the resource ID. However, because `a` is not a valid defined type
within the queried schema, what seems to be happening is that the resource
ID is completely ignored and the actual node type to be queried is determined
at random. Which means that in the end, one of the node types is randomly
queried with an invalid ID really, because what it's passed is the received
encoded value and not what is returned from the translator.

**Comment by benwilson512** [comment]
Can you show an example?

**Comment by satom99** [comment]
Sure thing, here's an [example repository](https://github.com/satom99/wine).

The following two possible queries are defined:

**Examples**
```gql
query{
  examples(first:5) {
    edges{
      node{
        id
        name
      }
    }
  }
}
```
which is a simple connection returning the following response
```json
{
  "data": {
    "examples": {
      "edges": [
        {
          "node": {
            "id": "RXhhbXBsZTox",
            "name": "Hello"
          }
        },
        {
          "node": {
            "id": "RXhhbXBsZToy",
            "name": "Bye"
          }
        }
      ]
    }
  }
}
```

**Node**
```gql
query{
  node(id:"RXhhbXBsZTox") {
    id
    ... on Example{
      name
    }
  }
}
```
which returns the following data
```json
{
  "data": {
    "node": {
      "id": "RXhhbXBsZTox",
      "name": "Hello"
    }
  }
}
```

---

Those are when specifying correct data. However, if we specify an invalid node ID:
```gql
query{
  node(id:"invalid") {
    id
    ... on Example{
      name
    }
  }
}
```
the global ID translator is returning ` {:error, "Could not decode ID value 'invalid'"}}` but \
the resolver callback is called regardless and a successful response is given, the same as before.

Now, this is not the issue I encountered originally really, but I guess we can have a look on this.

**Comment by benwilson512** [comment]
Ah. The parse node ids middleware needs to set the resolution state. will handle.

**Comment by benwilson512** [comment]
@satom99 Ah, so the actual thing that's happening here is that the node field resolver doesn't actually use the parse ids middleware.

In any case, this is handled in the latest 1.5.0-beta.0 release.

**Comment by satom99** [comment]
Much appreciated @benwilson512! :blush:

**Comment by satom99** [comment]
As a followup, I'm trying to get that release to work but no success so far.

After updating the dependencies to the latest `1.5.0-beta.0` release, the
same project does not compile. I am guessing this has to do with the fact
that absinthe itself was undergoing a major refactor and could have broken
some of the stuff that was working in previous versions. I have no idea, so I
figured I would ask here as it's somewhat still related. cc @benwilson512

**Comment by satom99** [comment]
Sure thing! Note the repository is [the same](https://github.com/satom99/wine) as for the above and the dependencies are [these](https://github.com/satom99/wine/blob/86522280180e9bca788a14ecf306afe897326312/mix.exs#L29-L31).

The exact error trace would be the following:
```
Compiling 10 files (.ex)

== Compilation error in file web/types/example.ex ==
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Absinthe.Blueprint.Schema.FieldDefinition.__struct__/1    
    
    The following arguments were given to anonymous fn/2 in Absinthe.Blueprint.Schema.FieldDefinition.__struct__/1:
    
        # 1
        :example
    
        # 2
        {%Absinthe.Blueprint.Schema.FieldDefinition{__private__: [], __reference__: %{location: %{file: "···/wine/web/types/example.ex", line: 13}, module: Wine.Type.Example}, arguments: [], complexity: nil, config: nil, default_value: nil, deprecation: nil, description: nil, directives: [], errors: [], flags: %{}, function_ref: nil, identifier: :node, middleware: [], module: Wine.Type.Example, name: "node", source_location: nil, triggers: [], type: :node}, []}
    
    lib/absinthe/blueprint/schema/field_definition.ex:7: anonymous fn/2 in Absinthe.Blueprint.Schema.FieldDefinition.__struct__/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/absinthe/blueprint/schema/field_definition.ex:7: Absinthe.Blueprint.Schema.FieldDefinition.__struct__/1
    (elixir) lib/kernel.ex:2147: Kernel.struct!/2
    lib/absinthe/schema/notation.ex:1426: Absinthe.Schema.Notation.scoped_def/5
    expanding macro: Absinthe.Schema.Notation.field/3
    web/types/example.ex:13: Wine.Type.Example (module)
    expanding macro: Absinthe.Relay.Node.Notation.node/2
```
And [this](https://github.com/satom99/wine/blob/86522280180e9bca788a14ecf306afe897326312/web/types/example.ex#L13) is the file that's originating the error.

**Comment by satom99** [comment]
Any update so far with regards to the issue above? @benwilson512 🙂

**Comment by benwilson512** [comment]
Hi @satom99 `node field` is not to be used for this purpose. `node field` creates the top level ` { node(id: "123") { ... on Example { id name } }` style field directly on the root query object. It does not take a `node_type` argument. Try removing `node_type` from your `node field` definition.

**Comment by satom99** [comment]
Hello @benwilson512. Removing `node_field` from the `node` call does not work.

Either way, it's worth noting that before updating to the beta branches, having
`node_type` worked without any compilation issues.

However, one of the issues we are noticing doing so is that sometimes the resolving node
does not correspond to the one defined. Per example, say we have two `node field` calls
for `fruit` and `vegetables` respectively. Now, when querying `node` with a `fruit` ID it is
sometimes resolved as if a `vegetables` ID was provided instead.

**Comment by benwilson512** [comment]
> before updating to the beta branches, having node_type worked without any compilation issues.

1.4 generally just ignored things that weren't in the right place, so that isn't necessarily an indicator that 1.5 is doing something wrong. 

> Per example, say we have two node field calls for fruit and vegetables respectively. 

You can't define a field in two places. It's a single GraphQL field, you need to define it one place. If you want to split the logic up you of course can by having the resolver function dispatch to different things based on the type. The field itself however needs to be defined in one place, usually directly under `query do`.
