### ISSUE TITLE
Support outputs containing edge fields

### ISSUE THREAD

**Issue by skosch** [absinthe-graphql/absinthe_relay#15]
As far as I can tell, it's not possible at this point to use RANGE_ADD, since the client expects a new edge containing the new node, instead of just the new node itself.

Maybe it's possible to add a new piece of notation, e.g. `edge(:type)` that wraps the final output in `edges { node {...}}` or similar (although I'm not sure how robust that approach would be, especially in light of facebook/relay#538 ... hopefully RANGE_ADD will soon be usable with multiple new nodes as well).

**Comment by bruce** [comment]
@skosch Can you give an example of what the resulting GraphQL result needs to look like? I don't understand based on this issue why you can't provide whatever fields you want (including an edge) in a mutation output type. The edge type for a connection is defined as `*_edge`, so, eg:

* `connection node_type: :pet` will give you an edge type, `:pet_edge`
* `connection :my_custom_connection, node_type: :pet` (supported by `master`, will be in v0.9.0) will give you `:my_custom_connection_edge`.

**Comment by skosch** [comment]
Just using `:pet_edge` and returning `%{node: {new_pet}}` works indeed. Thank you :+1:

**Comment by dotbear** [comment]
hey @skosch, I'm trying to get this to work, but my upsert is returning `null`. Am I returning the wrong value?

My return is

```elixir
    {:ok, %{node: post}}
```

my return type is

```
      output do
        field :post_edge, :post_edge
      end
```
