### ISSUE TITLE
[Absinthe v1.5.0-rc]: Connection default pagination args not configured

### ISSUE THREAD

**Issue by bgentry** [absinthe-graphql/absinthe_relay#153]
After upgrading all Absinthe dependencies to the latest v1.5 RC (and Absinthe itself on [`master@1495a09c`](https://github.com/absinthe-graphql/absinthe/commit/a98ee70d6a00fe1954df935b2f0447f6818ae833), I see these errors on all Relay connections I have defined:

```
     Assertion with == failed
     code:  assert response["errors"] == nil
     left:  [%{"message" => "Unknown argument \"first\" on field \"batches\" of type \"RootQueryType\"."}]
     right: nil
     stacktrace:
       test/graphql/batch_test.exs:357: MyApp.GraphQL.BatchTest.assert_returned_batches/3
       test/graphql/batch_test.exs:370: (test)
```

The connection definition is pretty simple for this connection:

```elixir
connection node_type: :batch do
    field :nodes, non_null(list_of(non_null(:batch))) do
      resolve(&MyApp.GraphQL.Helpers.resolve_conn_edge_nodes/2)
    end

    # edge is required since we're customizing this connection, even if empty:
    edge do
    end
  end
```

Glancing at the schema output confirms that none of these pagination args (`first`, `last`, etc) are defined anymore.

**Comment by benwilson512** [comment]
Hey @bgentry can you confirm that you're on the latest 1.5 Absinthe.Relay as well? What is the output of `mix deps|grep absinthe`?

**Comment by bgentry** [comment]
> can you confirm that you're on the latest 1.5 Absinthe.Relay as well?

Yes, I believe so @benwilson512 (unless something got released tonight):

```
➜  mix deps|grep absinthe
* absinthe 1.5.0-rc.2 (https://github.com/absinthe-graphql/absinthe.git) (mix)
* absinthe_relay 1.5.0-rc.0 (Hex package) (mix)
  locked at 1.5.0-rc.0 (absinthe_relay) e0db315e
* absinthe_sorting_codec 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (absinthe_sorting_codec) d865e516
* absinthe_plug 1.5.0-rc.1 (Hex package) (mix)
  locked at 1.5.0-rc.1 (absinthe_plug) c06e0674
* absinthe_phoenix 1.5.0-rc.0 (Hex package) (mix)
  locked at 1.5.0-rc.0 (absinthe_phoenix) 9a76cda0
```

**Comment by bgentry** [comment]
@benwilson512 please lmk if this turns out to be difficult to reproduce in any way, I'm happy to help wherever I can! You can ping me on Elixir Slack too.

**Comment by benwilson512** [comment]
@bgentry if you have time to create a failing test case PR on Absinthe.Relay you'd definitely save me time. Otherwise I'll try to get a look at it this weekend.

**Comment by bgentry** [comment]
I have added a failing test case for this issue in #156. I believe it's because we're not using the full functionality of `absinthe_relay` and are instead using only the Connections implementation. This worked prior to the v1.5 series (on v1.4) but is broken in these RCs.

**Comment by benwilson512** [comment]
Solution: Include this line in your root schema:

```
@pipeline_modifier Absinthe.Relay.Schema
```

**Comment by bgentry** [comment]
@benwilson512 I got time to try this out today and I can confirm that it works! Thanks for sorting it out and correcting the documentation (and my test case) :v:
