### ISSUE TITLE
Absinthe.Relay.Connection.Options

### ISSUE THREAD

**Issue by SimunKaracic** [absinthe-graphql/absinthe_relay#159]
The default type t of `Absinthe.Relay.Connection.Options` is wrong.
Parameters after and before are not integers, they are `Connection.cursor()`s.

https://github.com/absinthe-graphql/absinthe_relay/blob/master/lib/absinthe/relay/connection.ex#L5-L10

I'll open up a PR with the proposed changes.

**Comment by benwilson512** [comment]
PR welcome!

**Comment by SimunKaracic** [comment]
Additionally, the integers should probably be pos_integer(). I'll add that in too

**Comment by benwilson512** [comment]
Fixed by https://github.com/absinthe-graphql/absinthe_relay/pull/160
