### ISSUE TITLE
Update mix dependencies

### ISSUE THREAD

**Issue by sjchmiela** [absinthe-graphql/absinthe_relay#20]
It is currently not possible to use the latest RC of Ecto 2 (http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/) and the `absinthe_relay` at the same time. Would be grateful for releasing a new version or just a RC for now…

**Comment by benwilson512** [comment]
Can you gist the error you're getting? If it has to do with `:poison` you can simply add `override: true` to the poison dependency line.

**Comment by sjchmiela** [comment]
Nope, it has to do with `phoenix_ecto`, I'll post the exact error in 10 hours. Thanks for the quick response!

**Comment by benwilson512** [comment]
ah. You can just do `override: true`  on that too.

**Comment by sjchmiela** [comment]
Thanks! Solved the issue with:

```elixir
defp deps do
    […
     {:phoenix_ecto, "~> 3.0.0-rc", override: true},
     {:absinthe_plug, "~> 1.1"},
     …
    ]
  end
```

**Comment by ukasiu** [comment]
Just in case you had the same problem, you have to add `override: true` on `ecto` not `phoenix_ecto`
