### ISSUE TITLE
Node query returns wrong object

### ISSUE THREAD

**Issue by skosch** [absinthe-graphql/absinthe_relay#21]
Here's my situation: `Viewer` has a connection `years`; each `Year` has a connection `emails`.

```
node object :viewer do
    connection field :years, node_type: :year do
      resolve fn
        pagination_args, %{source: _} ->
          {:ok, list} = App.Resolver.Year.all(%{}, %{})
          {:ok, Absinthe.Relay.Connection.from_list(
            list, pagination_args
          )}
      end
    end
end

connection node_type: :year
node object :year do
  # ...
  connection field :emails, node_type: :email do
    resolve fn
      pagination_args, %{source: year} ->
        with {:ok, list} <- App.Resolver.Email.all_for_year(%{year_id: year.id}, %{}), do:
        {:ok, Absinthe.Relay.Connection.from_list(
          list, pagination_args
        )}
    end
  end
end
```
---
Let's get a year's emails:

```
query {
  yearByYear(year: 2016) {  # just a shortcut to some year object, so I can grab $year from the URL
    emails(first: 1) {
      edges {
        node {
          id
        }
      }
    }
  }
}
```
... that's no problem at all:
```
{
  "data": {
    "yearByYear": {
      "emails": {
        "edges": [
          {
            "node": {
              "id": "RW1haWw6MQ=="
            }
          }
        ]
      }
    }
  }
}
```
Alright, now let's ask for that email node directly by its global id:

```
query {
  node(id: "RW1haWw6MQ==") {
    id
    __typename
  }
}
```
... now this returns
```
{
  "data": {
    "node": {
      "id": "WWVhcjoxOA==",
      "__typename": "Year"
    }
  }
}
```
Wat. It's now returning the year the email belongs to.

Just to be clear, the `Email.find` resolver *is* being called; and the email *is* being returned, but then somewhere along the way Absinthe decides that it's dealing with a Year instead. This happens with all other "children" of `Year` but not with those of the `viewer`, which leads me to conjecture (though I haven't tested it) that this has to do with second-level connections.

There is a distinct possibility that this is due to some misconfiguration on my part, but I can't figure out what's wrong. It's insidious insofar as Relay often inserts `... on Node` (see facebook/relay#782 etc.) into mutation queries, and as a result those often come up emptyhanded when they shouldn't.

**Comment by bruce** [comment]
@skosch Can I see your `node interface do ... end` block?

**Comment by skosch** [comment]
Ahhhhhh. So much head-scratching, such a silly cause :dizzy_face: ... thanks @wbruce.

For others out there: make sure the resolver in `node interface` doesn't pattern-mismatch, i.e. make extra sure the patterns are unique and/or ordered by specificity in all circumstances and (edge) cases.

**Comment by bruce** [comment]
Thanks @skosch. In practice, I try to pattern match against the struct type, eg:

```elixir
node interface do
  resolve_type fn
    %Model.Foo{}, _ ->
     :foo
    _, _ ->
     nil
  end
end
```

Someday I should update the documentation to reflect that.

**Comment by skosch** [comment]
That's clever!

In my case `Year` only has a single field `year` (for now). But because of the Ecto association of other objects to a particular `year`, the pattern match on `%{year: _}` simply wasn't unique, and I had to move it to the back of the list to fix my problem. Maybe Absinthe could run all of the declared type structs through the `resolve_type` matcher at compile time and print a warning if any two of them return the same atom?

**Comment by skosch** [comment]
(This kind of "shadowing" edge case, I imagine, is also what keeps you from macro-ing away `resolve_type` altogether by simply matching struct types to type atoms inside of Absinthe.Relay?)

**Comment by bruce** [comment]
At its core, the reason `resolve_type` is there because the _internal_ representation of a object (eg, a model struct representing a database object) may or may not be the same as the GraphQL-exposed type. The schema designer is, of course, free to impose whatever convention they like. For instance, an example from our own code:

```elixir
node interface do
  resolve_type fn
  # Guess type from struct name:
  # Example: OurApp.Model.Foo -> :foo
  %{__struct__: str}, _ ->
      str
      |> OurApp.Model.Node.model_to_node_type
    value, _ ->
      Logger.warn "Could not extract node type from value: #{inspect value}"
      nil
  end
end
```

`OurApp.Model.Node.model_to_node_type/1` looks like this:

```elixir
  @doc """
  Given a model name, return the matching node type
  (Absinthe type identifier).

  ## Examples

      iex> model_to_node_type(OurApp.Model.AssetType)
      :asset_type
  
  """
  @spec model_to_node_type(atom) :: atom
  def model_to_node_type(model) do
    ["OurApp", "Model", name] = Module.split(model)
    name
    |> Macro.underscore
    |> String.to_existing_atom
  end
```
