### ISSUE TITLE
Do I need to add absinthe to deps?

### ISSUE THREAD

**Issue by hisapy** [absinthe-graphql/absinthe_relay#25]
Do I need to add **absinthe** to deps before adding **absinthe_relay**?

**Comment by benwilson512** [comment]
Nope, absinthe_relay has absinthe as a dependency, so absinthe is already added. You can see the list of a library's dependencies on hex: https://hex.pm/packages/absinthe_relay

**Comment by hisapy** [comment]
Thanks for the quick response
