### ISSUE TITLE
Default value for pagination

### ISSUE THREAD

**Issue by bart-j** [absinthe-graphql/absinthe_relay#26]
When not including pagination variables  in the GraphQL query, Absinthe throws an exception:

**Code**

```
connection field :cases, node_type: :case do
  resolve fn pagination_vars, _ ->
    {:ok, Absinthe.Relay.Connection.from_query(Case, &Repo.all/1, pagination_vars)}
  end
end
```

**GraphQL query**

```
query {
    cases {
        edges {
            title
        }
    }
}
```

**Exception**

```
Request: POST /graphql
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: 0
        (absinthe_relay) lib/absinthe/relay/connection.ex:324: Absinthe.Relay.Connection.from_query/4
```

When running the query including pagination parameters the query resolves just fine:

```
query {
    cases(first: 10) {
        edges {
            title
        }
    }
}
```

Maybe it is a good idea to include a default _first_ parameter, e.g. first 10. Would like to submit a pull request for that but I can use some directions for a proper fix.

**Comment by sjchmiela** [comment]
#31

**Comment by bruce** [comment]
So, I don't think a default makes sense here, but better error reporting (if `last` or `first` is not provided) is.
