### ISSUE TITLE
Pluggable / Extendable Global IDs

### ISSUE THREAD

**Issue by stavro** [absinthe-graphql/absinthe_relay#27]
I have a pretty extensive use case that I'm battling with where I need to use global ids that are more than a combination of `type` and `id` (specifically, they include shard-resolvable information for a multi-tenant environment).

It doesn't look like I can customize this global id currently.  Would love to see a more extensible approach! Let me know your thoughts and I'll see if I can help.

Thanks!

**Comment by bruce** [comment]
@stavro That's an interesting problem -- I think it's surmountable. I'll try fiddling with an approach this evening to see if I can find a decent, general-purpose solution.

**Comment by bruce** [comment]
@stavro My proposal:

We define a new behaviour, `Absinthe.Relay.Node.Registry` which defines the callbacks for `to_global_id/2` and `from_global_id/2`. A new module, `Absinthe.Relay.Node.Registry.Default`, adopts that behaviour and defines the current implementation. It is used as the default registry.

When defining your node interface, you can override the registry by passing an option:

```
node interface registry: YourCustomRegistry do
    resolve_type fn
      # ...
    end
  end
```

Calls to `Absinthe.Relay.Node.to_global_id/2` and `Absinthe.Relay.Node.from_global_id/2` would always lookup the node interface and use its registry (either default or custom), retaining backwards-compatibility.

BTW, I'm open to another name besides "Registry," it's just the first that came into my head.

**Comment by stavro** [comment]
Hmm... If you're thinking that `to_global_id/2` will have `(type, id)` as arguments, then I'm not sure it's flexible enough for what I need.

I'd like to really replace all of this logic (as well as the reverse operation): https://github.com/absinthe-graphql/absinthe_relay/blob/master/lib/absinthe/relay/node.ex#L224-L234

However:  I might be able to make it work by using the `id_fetcher` logic you have, and handing an opaque combined `shard_id + record_id` to absinthe in place of just the record's ID.

Let me try this and I'll give you feedback.

**Comment by bruce** [comment]
@stavro Sorry, no, you'd get the object (source) in addition to the type name, and the return value from from_global_id would also be more flexible. global_id_resolver (and a few other places) would be modified to suit, but I'd rather not force the registry to have to duplicate the error handling logic there.

It would help if you gave a specific example of where you'd get the information needed to build your IDs, and the data you'd like to get back from from_global_id.

**Comment by bruce** [comment]
Update: I'm currently working on this, and should have a PR out shortly to discuss.

**Comment by austinsmorris** [comment]
Any update on this?  Anything I can help with?

**Comment by bruce** [comment]
Sorry, I had to temporary pause on work here for various reasons -- to include ElixirConf and our focus on Absinthe 1.2, which is a complete rework of the validation and execution phases to support subscriptions, etc, -- and I lost my prototyping branch for this feature during a laptop wipe -- _groan_

We'll be out with the alpha for the new Absinthe release shortly; in the meantime if someone wants to pick this up, we'd appreciate the assistance (otherwise it will probably be an hold until the end of this week).

**Comment by leobessa** [comment]
Hey @bruce, can you update me on this issue? Is anyone working on it?

I'd be glad to work on a PR, but I might need some guidance.

**Comment by bruce** [comment]
I'm afraid not; unfortunately as we don't use Relay day-to-day, it's fallen out of the critical path a bit. If you'd like to take it on, we'd be happy to help point you in the right direction. We're pretty active in the #absinthe-graphql elixirlang Slack channel during US hours; that's probably the best way to talk through things -- and it will put you into contact with other people that are using Relay + Absinthe, too.

**Comment by bruce** [comment]
Closing this as stale. If someone wants to pick it up, we're happy to review a PR.
