### ISSUE TITLE
Provide plug that accepts batched queries

### ISSUE THREAD

**Issue by skosch** [absinthe-graphql/absinthe_relay#28]
As per Slack discussion with @benwilson512, I'd like to suggest that Absinthe should accept arrays of queries in the style of:

``` json
[{
  "id": "q1",
  "query": "query Index {vie ...",
  "variables": {}
}, {
  "id": "q2",
  "query": "query ...",
  "variables": {}
}]
```

The results should mirror this structure, as noted in the README of https://github.com/nodkz/react-relay-network-layer. The new plug can be documented as a solution to facebook/relay#724, when used in combination with react-relay-network-layer.

**Comment by tlvenn** [comment]
On a side note, Transport-level batching (what you are implementing now) will be supported by Apollo Client as well very soon. So this will be useful beyond Relay.

**Comment by skosch** [comment]
That's an interesting note, thanks! Maaaybe that means this shouldn't necessarily be part of the Absinthe.Relay package then, but instead an extension of Absinthe.Plug after all? This came up on Slack yesterday with @benwilson512 as well – what do you think?

**Comment by tlvenn** [comment]
This is currently tracked there: https://github.com/apollostack/apollo-client/issues/505
And indeed, probably worth pulling this outside of Absinthe_Relay.

**Comment by benwilson512** [comment]
Noted, let's do that. Presumably it's the same structure as Relay?

**Comment by bruce** [comment]
Closing this; moved to absinthe_plug. See absinthe-graphql/absinthe_plug#34 for current details.
