### ISSUE TITLE
Question about RANGE_ADD mutation_type

### ISSUE THREAD

**Issue by hisapy** [absinthe-graphql/absinthe_relay#30]
In the Star Wars Relay example, there is an  [AddShipMutation](https://github.com/iporaitech/pwr2-docker/blob/master/web/static/js/star_wars/mutation/AddShipMutation.js) which has the following config

``` javascript
// ...
  getConfigs() {
    return [{
      type: 'RANGE_ADD',
      parentName: 'faction',
      parentID: this.props.faction.id,
      connectionName: 'ships',
      edgeName: 'newShipEdge',
      rangeBehaviors: {
        '': 'append',
        'orderby(oldest)': 'prepend',
      },
    }];
  }
// ....
```

**Notice that `RANGE_ADD` needs to be specified with an `edgeName`**

The schema.js in the example [imports cursorFromObjectInConnection() from graphql-relay](https://github.com/relayjs/relay-examples/blob/master/star-wars/data/schema.js#L28)   and use that function to [calculate a cursor in the outputFields of the mutation](https://github.com/relayjs/relay-examples/blob/master/star-wars/data/schema.js#L278). 

To implement the same mutation in Absinthe.Relay [I had to get the cursor](https://github.com/iporaitech/pwr2-docker/blob/master/web/graphql/schema.ex#L77) _manually_.

Do you think we need a `cursor_from_object_in_connection()/2` in Absinthe.Relay to handle `RANGE_ADD` output the same way than in graphql-relay Javascript imlementation?

**Comment by panayi** [comment]
In your [example](https://github.com/iporaitech/pwr2-docker/blob/master/web/graphql/star-wars/mutations.ex#L38), couldn't you do:

```
Connection.offset_to_cursor(length(faction.ships) - 1)
```

**Comment by hisapy** [comment]
Maybe yes @panayi ... at the moment I was writing the example I believe I didn't know about the function `Connection.offset_to_cursor`. 

Anyway, the idea, based on the Javascript implementation is to return the cursor for the recently added object and thus, I _believe_ your latter suggestion seems more appropriate in case someone else is adding ships to a faction.

**Comment by hisapy** [comment]
Hello again. 

I have some more questions regarding `RANGE_ADD` mutation. Suppose I have the following mutation in Relay

```javascript
import Relay from 'react-relay';

export default class AddMemberMutation extends Relay.Mutation {
  getMutation() {
    return Relay.QL`mutation {addMember}`;
  }

  getVariables() {
    const { member } = this.props;

    return {
      ...member
    };
  }

  getFatQuery() {
    return Relay.QL`
      fragment on AddMemberPayload {
        club { members },
        newMemberEdge,
        errors
      }`;
  }

  getConfigs() {
    return [{
      type: 'RANGE_ADD',
      parentName: 'club',
      parentID: this.props.club.id,
      connectionName: 'members',
      edgeName: 'newMemberEdge',
      rangeBehaviors: {
        '': 'append'
        'status(active)': 'prepend'
      }
    }];
  }
}
```

I'm trying to understand the following:

a. How do we know the page info to be used to return the Club's membersConnection in the mutation?. For example, `Connection.from_query` needs some page info like `first: 10` to know what "page" to return.
b. Supposing I figured out what connection to return, how can determine the cursor of the `newMemberEdge` without having to cycle through the edges to find the corresponding member?

**Comment by bruce** [comment]
I'm closing this as stale / out of scope, as it's really more a question about Relay's JS side (and questions like this are probably better addressed in Slack).
