### ISSUE TITLE
hasNextPage lies

### ISSUE THREAD

**Issue by sjchmiela** [absinthe-graphql/absinthe_relay#32]
[Implemented way of checking for `hasNextPage` value](https://github.com/absinthe-graphql/absinthe_relay/blob/e48ac8693c54f71bbcacabbda0f81caa43c5c6da/lib/absinthe/relay/connection.ex#L344) is wrong when the number of edges in a connection is divisible by the limit value.

``` Elixir
has_next_page: !(length(records) < limit),
```

Imagine a connection with 30 records, we will paginate them by 10.
1. We see records 1...10, `hasNextPage: !(30 < 10) == true`.
2. We see records 11...20, `hasNextPage: !(30 < 20) == true`.
3. We see records 21...30, `hasNextPage: !(30 < 30) == true`, while there is no more records.

**Comment by bruce** [comment]
Thanks @sjchmiela -- good investigation. Would love a PR if you have the time to put one together.

**Comment by benwilson512** [comment]
This should be fixed by the merged PR.
