### ISSUE TITLE
Splitting up mutations

### ISSUE THREAD

**Issue by leighshepperson** [absinthe-graphql/absinthe_relay#45]
I'm creating quite a few large mutations and I want to split the input and output of a mutation into different modules. 

My approach is something like this:

```
  input_object :customer_input do
    field :client_mutation_id, non_null(:string)
    field :name, non_null(:string)
  end

  object :customer_output do
    field :id, :integer
  end
```

```
  object :customer_payloads do
    payload field :customer do
      input do: import_fields :customer_input
      output do: import_fields :customer_output
      resolve fn(_, _) -> {:ok} end
    end
  end
```

To get it working, I've just had to add the `client mutation id` to the input object. 

Is this good enough - or will it be missing something important. 

Or - is there a better way to do this?

Ideally, there would be something like this:

```
 payload field :customer, :customer_input, :customer_output do
    resolve...
 end
```
Or some similar combination

Of course, you can do this by defining the whole payload elsewhere and importing the fields into the root schema

**Comment by bruce** [comment]
Sorry about the (very) late reply on this. Before I close this, let me point to an example using macros to build up patterns -- it might serve as a useful tool to generate some of the boilerplate here. (Note that I think the use of `import_fields` is fine.)

This example illustrates how to build enum values from an external definition, but it's still a useful illustration:
https://gist.github.com/bruce/e5307411f757c6ac585005d7f8f37e68
