### ISSUE TITLE
Add totalCount field to connections

### ISSUE THREAD

**Issue by zipme** [absinthe-graphql/absinthe_relay#48]
How do you add total_count info to the connection?

I am stuck here

```elixir
  connection node_type: :pet do
    field :count, :integer do
      resolve fn _, %{source: conn} ->
        count = # how do you get the total count of the pets?
        {:ok, count}
      end
    end
  end
```

And here is the resolver:

```elixir
def pets(args) do
  conn = Pet |> Relay.Connection.from_query(&Repo.all/1, args)
  {:ok, conn}
end
```

Thanks!

**Comment by bruce** [comment]
See the example here: https://gist.github.com/bruce/52b1528af5ce446eb24eae3cd32b6af7

Thanks!

**Comment by gottfrois** [comment]
Great thx ! Have you consider adding this into the documentation?

**Comment by benwilson512** [comment]
PR welcome!

**Comment by jeroenvisser101** [comment]
@bruce is it possible to extend pageInfo and add the count there?

**Comment by bucha** [comment]
@bruce GOLD! You just saved my Sunday!

**Comment by ug0** [comment]
In the [gist](https://gist.github.com/bruce/52b1528af5ce446eb24eae3cd32b6af7) example, the `count` is calculated every time no matter the client want the `count` field or not. 

I wonder if it's a better idea to put only the `query` to the parent(items) result, and calculate the count at the `count` field level. For example:

```elixir
connection node_type: :item do
  field :count, :integer do
    resolve fn parent, _, _ ->
      count = Repo.aggregate(parent.count_query, :count, :id)
      {:ok, count}
    end
  end

  edge do
  end
end

query do
  connection field :items, node_type: :item do
    resolve fn _, args, _ ->
      query = from t in Item
      {:ok, result} = Absinthe.Relay.Connection.from_query(query, &Repo.all/1, args)
      {:ok, Map.put(result, :count_query, query}
    end
  end
end
```

**Comment by margusp2heathmont** [comment]
How to add totalCount to pageInfo?

**Comment by cheerfulstoic** [comment]
I wanted to be able to do this more generally rather than needing to customize my `connection field ...` definitions everywhere.  So I created a middleware that does this:

https://gist.github.com/cheerfulstoic/4f676f0b5de42f3f5f60d06ae03c4dfc

I especially like how you have control over if it runs by choosing to return the `RelayConnectionLazyEvaluate.Value` struct or not for the field.  I think it allows for easier following of the code for people coming behind (because the struct is nested within the middleware)

**Comment by martasd** [comment]
There's an example about how to do this in the Absinthe.Relay docs: https://hexdocs.pm/absinthe_relay/Absinthe.Relay.Connection.html#module-customizing-types

**Comment by kasvith** [comment]
> In the [gist](https://gist.github.com/bruce/52b1528af5ce446eb24eae3cd32b6af7) example, the `count` is calculated every time no matter the client want the `count` field or not.
> 
> I wonder if it's a better idea to put only the `query` to the parent(items) result, and calculate the count at the `count` field level. For example:
> 
> ```elixir
> connection node_type: :item do
>   field :count, :integer do
>     resolve fn parent, _, _ ->
>       count = Repo.aggregate(parent.count_query, :count, :id)
>       {:ok, count}
>     end
>   end
> 
>   edge do
>   end
> end
> 
> query do
>   connection field :items, node_type: :item do
>     resolve fn _, args, _ ->
>       query = from t in Item
>       {:ok, result} = Absinthe.Relay.Connection.from_query(query, &Repo.all/1, args)
>       {:ok, Map.put(result, :count_query, query}
>     end
>   end
> end
> ```

This gives an error with dializer

**Comment by ChrisNg02655332** [comment]
> In the [gist](https://gist.github.com/bruce/52b1528af5ce446eb24eae3cd32b6af7) example, the `count` is calculated every time no matter the client want the `count` field or not.
> 
> I wonder if it's a better idea to put only the `query` to the parent(items) result, and calculate the count at the `count` field level. For example:
> 
> ```elixir
> connection node_type: :item do
>   field :count, :integer do
>     resolve fn parent, _, _ ->
>       count = Repo.aggregate(parent.count_query, :count, :id)
>       {:ok, count}
>     end
>   end
> 
>   edge do
>   end
> end
> 
> query do
>   connection field :items, node_type: :item do
>     resolve fn _, args, _ ->
>       query = from t in Item
>       {:ok, result} = Absinthe.Relay.Connection.from_query(query, &Repo.all/1, args)
>       {:ok, Map.put(result, :count_query, query}
>     end
>   end
> end
> ```

perfect !!!
