### ISSUE TITLE
Use Absinthe.Relay.Node.ParseIDs with input_object

### ISSUE THREAD

**Issue by diegonogueira** [absinthe-graphql/absinthe_relay#53]
Is there any way to use Absinthe.Relay.Node.ParseIDs with input_object? How to convert (id, type_id) from global_id.

```elixir
  input_object :address_for_save do
    field :id, :id
    field :value, :integer
    field :type_id, :id
  end
```

Thanks

**Comment by diegonogueira** [comment]
I'm using v1.3 branch. :)

**Comment by bruce** [comment]
There isn't currently. You could probably make your own middleware based on it, and support complex keys (eg, using update_in).

Otherwise you'll have to manually pull the values out in your resolvers and use the normal conversion functions.
