### ISSUE TITLE
Parsing nested ids

### ISSUE THREAD

**Issue by jsteiner** [absinthe-graphql/absinthe_relay#56]
Absinthe currently has the `ParseIDs` middleware, which converts ids for the top level object. It would be nice to have an easy way to parse the ids of nested objects as well. For example if you had

```
{
  foo {
    id
    baz {
      id
    }
    bars {
      id
    }
  }
}
```

It would parse the id of `foo`, `baz` and all the `bars` (assuming it's a has_many).

**Comment by benwilson512** [comment]
Just so we're clear, this is talking about inputs right? So it'd look like:
```
someField(input: {foo: {id: "ugly-node-id", parent: {id: "another-node-id"}}}) {...}
```

**Comment by jsteiner** [comment]
@benwilson512 yep, sorry, should have made that more clear (I'm still pretty new to GraphQL). Do you think something like this makes sense as an API?

```
middleware Absinthe.Relay.Node.ParseIDs,
  foo: [
    id: [:foo, :some_other_type],
    baz: [
      id: :baz
    ],
    bars: [
      id: :bar
    ]
  ]
```

Basically, it would do something similar to what it does now, but in the case that the value is another keyword list it would recurse.

**Comment by benwilson512** [comment]
Yup, that seems like the right way to go!

**Comment by benwilson512** [comment]
Handled in master
