### ISSUE TITLE
Incorrect documentation around connection definitions?

### ISSUE THREAD

**Issue by thaterikperson** [absinthe-graphql/absinthe_relay#60]
I'm not sure if this is just incorrect documentation or a larger error at [connection.ex#L52](https://github.com/absinthe-graphql/absinthe_relay/blob/6a2fcda17a4360ddb2e78811c6eb59e8167b9bca/lib/absinthe/relay/connection.ex#L52).

The resolve function returns `{:ok, connection}` but that gives me the following `BadMapError`.

```
** (BadMapError) expected a map, got: {:ok, %{edges: [%{cursor: "Y…
```

If I return the connection only instead of the tuple, the error goes away and everything seems to work correctly.

From my limited Absinthe experience, all resolve functions return a `{:ok, X}` tuple, which leads me to believe the documentation is correct, and the handling of the connection's resolve function is incorrect.

Here's my full, working schema:

```elixir
defmodule MyApp.Web.GraphQL.Schema do
  use Absinthe.Schema
  use Absinthe.Relay.Schema

  node interface do
    resolve_type fn
      %{email: _}, _ ->
        :user
      %{name: _}, _ ->
        :policy
      _, _ ->
        nil
    end
  end

  @desc "A Policy"
  node object :policy do
    field :id, non_null(:id)
    field :name, non_null(:string)
  end

  connection node_type: :policy

  @desc "A User"
  node object :user do
    field :id, non_null(:id)
    field :email, non_null(:string)
    field :name, non_null(:string)
    connection field :policies, node_type: :policy do
      resolve fn (pagination_args, %{source: _user}) ->
        connection = Absinthe.Relay.Connection.from_list(
          Policies.list_policies,
          pagination_args
        )
        connection
      end
    end
  end

  query do
    field :user, :user do
      arg :id, non_null(:id)
      resolve fn %{id: id}, %{context: _context} ->
        {:ok, Accounts.get_user(id)}
      end
    end
  end
end
```

**Comment by benwilson512** [comment]
Ah yes, the documented example is out of date. It used to be accurate but was not corrected when some of the Absinthe.Relay code was updated.

**Comment by thaterikperson** [comment]
If its only the documentation that need to be updated, I'm happy to submit a PR for it.

**Comment by benwilson512** [comment]
Please feel free!
