### ISSUE TITLE
Add middleware to specific node fields

### ISSUE THREAD

**Issue by Un3qual** [absinthe-graphql/absinthe_relay#68]
How do I add middleware to specific resolvers? For example, if I have
```elixir
query do
    node field do
      resolve fn
        %{type: :post, id: id}, _ ->
          Web.PostResolver.find(nil, %{id: id}, nil)
        %{type: :user, id: id}, _ ->
          # I only want my middleware to apply to this one
          # I can't just add
          middleware MyApp.Middleware.EnsureAuthenticated # <-- Doesn't work
          # Here because it's inside the resolve block
          Web.UserResolver.find(%{id: id}, nil)
      end
    end
end
```
I could add it above `resolve fn`, but then it would apply to all of the resolvers.

**Comment by Un3qual** [comment]
I'm an idiot. So sorry for wasting your time. I just didn't understand how this was supposed to work. 😢

**Comment by bruce** [comment]
It's far more likely that the documentation is unclear and we can do better! Did you figure out the problem?

Also, worth noting we're usually available in the #absinthe-graphql Slack channel if you want to dig into questions.

**Comment by Un3qual** [comment]
@bruce The documentation has worked great for me so far. My issue here was that I didn't understand what a node was with respect to relay.
