### ISSUE TITLE
Allow null for after argument

### ISSUE THREAD

**Issue by ssomnoremac** [absinthe-graphql/absinthe_relay#78]
Using Absinthe 1.4.0-beta.3 A-relay 1.3.4

Passing null for the after arg is apparently how the latest Relay Modern spec says is how to handle initial calls. 
    
    shifts(first:10, after: null)

However, this is breaking 
```
 ** (FunctionClauseError) no function clause matching in Base.decode64/2
        (elixir) lib/base.ex:309: Base.decode64(nil, [])
        (absinthe_relay) lib/absinthe/relay/connection.ex:466: Absinthe.Relay.Connection.cursor_to_offset/1
        (absinthe_relay) lib/absinthe/relay/connection.ex:422: Absinthe.Relay.Connection.offset/1
        (absinthe_relay) lib/absinthe/relay/connection.ex:373: Absinthe.Relay.Connection.offset_and_limit_for_query/2
        (absinthe_relay) lib/absinthe/relay/connection.ex:344: Absinthe.Relay.Connection.from_query/4
        (absinthe) lib/absinthe/resolution.ex:184: Absinthe.Resolution.call/2

```

Removing the after arg the query works

**Comment by bruce** [comment]
So fixing this will require we peg the `absinthe` dependency at `~> 1.4.0`, as it's the release that supports null literals.

That's scheduled for stable release on or around ElixirConf, in conjunction with the subscriptions code that @benwilson512 is polishing.

As such, a fix for this will probably get folded into _this_ package's v1.4, which I'm working on in the `next` branch / PR #75. I'll try to get a pre-release package out shortly targeting the latest absinthe v1.4 beta/rc.
