### ISSUE TITLE
Root Viewer query support

### ISSUE THREAD

**Issue by gauravtiwari** [absinthe-graphql/absinthe_relay#8]
Hey @bruce 

How does root viewer queries are supported in this package? For example: Reading a list of posts from server on index page. 

Here is how I am implementing it in a Phoenix app. Looks ok?

```elixir
object :post do
  field :id, :id
  field :title, :string
  field :description, :string
end

connection node_type: :post
```
`1. viewer_type.ex`
```elixir
# A viewer type with connection to posts
  object :viewer do
    field :id, :id
    connection field :posts, node_type: :post do
      resolve fn
        pagination_args, %{source: post} ->
          Connection.from_list(
            Repo.all(Post),
            pagination_args
          )
      end
    end
  end
```

`2. viewer.ex`
```elixir
# A simple struct with ID to hack root query
defmodule Blog.Viewer do
  def __struct__ do
    %{id: "root"}
  end
end
```

`3. schema.ex`
```elixir
# Main schema - I am initializing the viewer struct
  query do
    field :root,
     type: :viewer,
     resolve: fn
       _, _ -> {:ok, %Viewer{}}
     end
  end
```

This is client Client side relay query: 

```javascript
const PostsContainer = Relay.createContainer(Posts, {
  initialVariables: {
    count: 2,
    order: '-id',
  },
  fragments: {
    posts: () => Relay.QL`
      fragment on Viewer {
        id,
        posts(first: $count){
          pageInfo {
            hasPreviousPage
            hasNextPage
          }
          edges {
            node {
              id,
              title
            }
          }
        }
      }
    `,
  },
});
```
`query FindPosts{root{...F0}} fragment F0 on Viewer{id,_posts4jOdEP:posts(first:2){pageInfo{hasPreviousPage,hasNextPage},edges{node{id,title},cursor}}}`

but it seems that something is wrong in between. The client or the server isn't throwing any error, only this warning: `(program):245 Invalid count value : Relay Pending query Tracker` on client

If I remove the `posts` connection request from query, it does return fine the ID of the Struct. 
```json
posts: Object
__dataID__:"root"
id:"root"
```
It seems that response is messed up compared to what relay is expecting it to be. Any pointers?

**Comment by skosch** [comment]
I just ran into the same error message.

In your case, @gauravtiwari, I think you need to use the `node` prefix macro for (at least) your `post` objects, and add a `node` query (pseudo-)field to allow Absinthe to do the mapping from internal to global id. (Sorry – it's been a month so probably no longer relevant.)

To @bruce & friends, I was only able to see the actual error message (`"No source non-global ID value could be fetched from the source object"`) by looking at the raw response to the query in the browser's network inspector; I propose that this case should lead to a crash. The message itself could be improved by hinting at the solution, e.g. `make sure you have set up a 'node field' query, and that the results of its resolver function include an 'id' field (or whatever internal id field your custom id fetcher looks for).`

**Comment by bruce** [comment]
@skosch I agree on the problem with @gauravtiwari (and I'm sorry we didn't respond to this sooner).

Since it's possible that an ID field might exist for an ID fetcher -- but the data may be `nil` -- I think blowing up is a bad idea. (In general, we only raise exceptions 1) at compile time, 2) when we're sure the error is for the schema designer and not the end user. We default to returning standard GraphQL errors in most cases. I do think a case could be made for using `Logger.warn` in events like this, however.)

Closing this issue, happy to address this narrower messaging issue in a separate item.
