### ISSUE TITLE
Allow null on ParseIDs

### ISSUE THREAD

**Issue by diegonogueira** [absinthe-graphql/absinthe_relay#82]
Using absinthe 1.4.0-rc.2 and absinthe_relay 1.3.

ParseIDs does not accept nil values. Maybe, it should ignore decode from nil values...

```
FunctionClauseError{args: nil, arity: 2, clauses:
nil, function: :decode64, kind: nil, module: Base}
, stack: [{Base, :decode64, [nil, []], [file: 'lib
/base.ex', line: 391]} ...
```

thanks,

**Comment by benwilson512** [comment]
Similar to https://github.com/absinthe-graphql/absinthe_relay/issues/78
