### ISSUE TITLE
Support for meta when using the payload macro

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe_relay#98]
Absinthe lets us define some meta on pretty much any types but it does not seem like this is supported with the payload macro.

Example:

```elixir
payload field :my_mutation do
  meta foo: 5
  input do
    field :test_id, non_null(:id), meta: [bar: "nice"]
  end
  output do
   field :my_payload, :my_object
  end
end
```

**Comment by tlvenn** [comment]
Hi @bruce, since I am not super comfortable with macros, I dont feel like meddling with your code. Any chance you could have a look ? Thanks in advance !

**Comment by bruce** [comment]
Sure, I’ll try to give this a look today.

**Comment by tlvenn** [comment]
Thanks a lot in advance @bruce !

**Comment by bruce** [comment]
The macro is `meta/2`, so you need to pass the key and value vs a keyword list. (One of the great pains in the macro approach as its currently implemented how hard it is to catch even wrong-arity use, something we're going to endeavor to fix.)

FWIW, this seems to work fine for me:

```elixir
mutation do
  payload field :simple_mutation do
    meta :foo, 5
    # ...
  end
end
```

I see `{:meta, [foo: 5]}` in the `%Absinthe.Type.Field{}`'s `:__private__` storage.

If you still see the issue, let's reopen this issue and dig a little deeper.

**Comment by tlvenn** [comment]
Haa I guess when I tried I didnt use the correct arity and then assumed that the payload macro was messing with it somehow.

How can I attach meta to the field input macro in the input, should I just use the `do end` syntax and place the meta inside ?

**Comment by tlvenn** [comment]
@bruce , do you think it would be possible to define a meta inline at the field level without opening a `do end` block ?

Something like this:

```elixir
field :age, :integer, description: "How old the item is", meta: {key, value}
```

**Comment by bruce** [comment]
I’m sure it’s possible given a little work. You’d want to support a keyword list, likely. (Similarly, the meta macro could be modified to accept a keyword list).
